// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Repository.Context;

namespace Repository.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200227144041_IspravkaHuawei")]
    partial class IspravkaHuawei
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Domain.Products.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Discount")
                        .HasColumnType("integer");

                    b.Property<Guid>("Identifier")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Tags")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 400, DateTimeKind.Local).AddTicks(1402),
                            Description = @"
                        <table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 width=""100%""
                         style='width:100.0%;mso-cellspacing:0cm;mso-yfti-tbllook:1184;mso-padding-alt:
                         0cm 0cm 0cm 0cm'>
                         <tr style='mso-yfti-irow:0;mso-yfti-firstrow:yes'>
                          <td width=""15%"" rowspan=2 valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Model<o:p></o:p></span></b></p>
                          </td>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Naziv<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Huawei P30 Lite Dual SIM 128GB 4GB
                          RAM (plava)</span></b><span lang=EN-US style='font-size:12.0pt;font-family:
                          ""Times New Roman"",serif;mso-fareast-font-family:""Times New Roman""'><o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:1'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Poznat kao<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>MAR-LX1A</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'><o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:2'>
                          <td width=""15%"" rowspan=5 valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Osnovno<o:p></o:p></span></b></p>
                          </td>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Market<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Mreže:</span></b><span lang=EN-US
                          style='font-size:12.0pt;font-family:""Times New Roman"",serif;mso-fareast-font-family:
                          ""Times New Roman""'> 850Mhz, 900Mhz, 1800Mhz, 1900Mhz, 2100Mhz, 2600Mhz,
                          HSDPA, LTE<o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:3'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Kućište<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Dimenzije:</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'> 152.9 x 72.7 x 7.4 mm<o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:4'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Procesor<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Tip:</span></b><span lang=EN-US
                          style='font-size:12.0pt;font-family:""Times New Roman"",serif;mso-fareast-font-family:
                          ""Times New Roman""'> Octa-core, Hisilicon Kirin 710, Mali-G51 MP4<br>
                          <b>Takt:</b> Quad-core 2.2 GHz Cortex-A73 &amp; Quad-core 1.7 GHz Cortex-A53<o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:5'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Baterija<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Vrsta:</span></b><span lang=EN-US
                          style='font-size:12.0pt;font-family:""Times New Roman"",serif;mso-fareast-font-family:
                          ""Times New Roman""'> Li-Po (baterija nije zamenjiva bez asistencije servisa)<br>
                          <b>Kapacitet:</b> 3340 mAh<br>
                          <b>Režim razgovora:</b> do 22 h (3G)<br>
                          <b>Stand by režim:</b> do 595 h (3G)<o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:6'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Ostalo<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Ostalo:</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'> dual sim, vibracija, senzor
                          otisak prsta, digitalni kompas, akcelerometar, Gyroscope<o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:7'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Ekran<o:p></o:p></span></b></p>
                          </td>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Glavni<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Tip:</span></b><span lang=EN-US
                          style='font-size:12.0pt;font-family:""Times New Roman"",serif;mso-fareast-font-family:
                          ""Times New Roman""'> LTPS IPS LCD (6.15 inča) capacitive<br>
                          <b>Broj boja:</b> (24-bit) 16.777.216 boja<br>
                          <b>Rezolucija:</b> 1080x2312 piksela<br>
                          <b>Ostalo:</b> osetljiv na dodir, sposobnost dodira ekrana da registruje više
                          različitih pozicija, EMUI 9.0<o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:8'>
                          <td width=""15%"" rowspan=2 valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Kamera<o:p></o:p></span></b></p>
                          </td>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Glavna<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Orijentacija sočiva:</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'> sa zadnje strane<br>
                          <b>Broj piksela senzora:</b> 48 MP (f1.8, wide, PDAF) + 8 MP (13mm ultrawide)
                          + 2 MP (f/2.4, depth sensor)<br>
                          <b>Rezolucija fotografija:</b> 5290x4512 piksela<br>
                          <b>Rezolucija videa:</b> 1080p@30fps (gyro-EIS)<br>
                          <b>Ostalo:</b> video zapis, LED blic, digitalni zoom, automatsko označavanje
                          lokacije, detekcija lica, HDR, panorama mod<o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:9'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Pomoćna<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Orijentacija sočiva:</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'> sa prednje strane<br>
                          <b>Broj piksela senzora:</b> 24 megapiksela<br>
                          <b>Rezolucija videa:</b> 1080p@30fps<br>
                          <b>Ostalo:</b> f/2.0, HDR<o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:10'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Zvuk<o:p></o:p></span></b></p>
                          </td>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Reprodukcija<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Zvučnici:</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'> mono zvučnik sa ugrađenim
                          pojačalom<br>
                          <b>Melodije:</b> polifone<br>
                          <b>Format melodija:</b> mp3, aac, aac+, eaac+, flac, wav, ogg, midi, amr<br>
                          <b>Ostalo:</b> spikerfon, specijalan mikrofon za smanjenje buke<o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:11'>
                          <td width=""15%"" rowspan=2 valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Memorija<o:p></o:p></span></b></p>
                          </td>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Interna<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Kapacitet:</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'> 128 GB (4 GB RAM)<o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:12'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Eksterna<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Formati:</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'> microSD (Trans Flash),Maximalno
                          podržano : 512 GB (shared SIM slot)<br>
                          <b>Uz aparat:</b> ne ide kartica<o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:13'>
                          <td width=""15%"" rowspan=3 valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Softver<o:p></o:p></span></b></p>
                          </td>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Operativni <br>
                          sistem<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Tip:</span></b><span lang=EN-US
                          style='font-size:12.0pt;font-family:""Times New Roman"",serif;mso-fareast-font-family:
                          ""Times New Roman""'> Android OS<br>
                          <b>Verzija:</b> v9.0 (Pie)<br>
                          <b>Formati:</b> mpeg4, H.263, H.264, xvid, wmv<o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:14'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Java<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Profil:</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'> ne<br>
                          <b>Konfiguracija:</b> podržava isključivo Nano SIM karticu, čitač dokumenata<o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:15'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Funkcije<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Osnovne:</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'> kalkulator, kalendar, alarm,
                          digitalni sat, notes, podsetnik, štoperica<br>
                          <b>Napredne:</b> komandovanje glasom, pozivanje glasom, snimanje glasa<o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:16'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Komunikacija<o:p></o:p></span></b></p>
                          </td>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Udaljeno<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Prenos podataka:</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'> GSM (9,6 Kb/s), GPRS (115 Kb/s),
                          EDGE (236 Kb/s), HSDPA, LTE<br>
                          <b>WAP pretraživač:</b> HTML5<br>
                          <b>Email protokoli:</b> IMAP, POP3, SMTP, Microsoft Exchange<br>
                          <b>Ostalo:</b> SMS, MMS, Email, Push Mail, IM<o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:17;mso-yfti-lastrow:yes'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Povezivanje<o:p></o:p></span></b></p>
                          </td>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Podržane <br>
                          tehnologije<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>GPRS:</span></b><span lang=EN-US
                          style='font-size:12.0pt;font-family:""Times New Roman"",serif;mso-fareast-font-family:
                          ""Times New Roman""'> da<br>
                          <b>EDGE:</b> da<br>
                          <b>3G:</b> da, HSDPA, 42 Mbps; HSUPA, 5.76 Mbps; LTE, Cat6, 50 Mbps UL, 300
                          Mbps DL<br>
                          <b>WLAN:</b> da, Wi-Fi 802.11 a/b/g/n/ac, dual-band, Wi-Fi hotspot, Wi-Fi
                          Direct<br>
                          <b>Bluetooth:</b> da, v4.2 sa A2DP, LE, aptX HD<br>
                          <b>USB i spikerfon:</b> da, microUSB v2.0 (Type-C 1.0 reversible connector),
                          3.5' audio<br>
                          <b>GPS:</b> da, sa A-GPS podrškom i GLONASS, BDS<o:p></o:p></span></p>
                          </td>
                         </tr>
                        </table>",
                            Discount = 0,
                            Identifier = new Guid("8e853b83-55ab-4562-bd90-4af0a8d3f027"),
                            Name = "Huawei P30 Lite Dual SIM 128GB 4GB RAM",
                            Price = 500m,
                            Tags = "Phones;Huawei;P30;Lite;",
                            UpdatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 400, DateTimeKind.Local).AddTicks(1409)
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 401, DateTimeKind.Local).AddTicks(6645),
                            Description = @"
                        <table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 width=""100%""
                         style='width:100.0%;mso-cellspacing:0cm;mso-yfti-tbllook:1184;mso-padding-alt:
                         0cm 0cm 0cm 0cm'>
                         <tr style='mso-yfti-irow:0;mso-yfti-firstrow:yes'>
                          <td width=""15%"" rowspan=2 valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Model<o:p></o:p></span></b></p>
                          </td>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Naziv<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Huawei P20 Dual SIM 64GB 4GB RAM
                          (twilight plava)</span></b><span lang=EN-US style='font-size:12.0pt;
                          font-family:""Times New Roman"",serif;mso-fareast-font-family:""Times New Roman""'><o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:1'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Poznat kao<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>EML-L29, EML-L09</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'><o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:2'>
                          <td width=""15%"" rowspan=5 valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Osnovno<o:p></o:p></span></b></p>
                          </td>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Market<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Mreže:</span></b><span lang=EN-US
                          style='font-size:12.0pt;font-family:""Times New Roman"",serif;mso-fareast-font-family:
                          ""Times New Roman""'> 850Mhz, 900Mhz, 1800Mhz, 1900Mhz, 2100Mhz, 2600Mhz,
                          HSDPA, LTE<o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:3'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Kućište<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Dimenzije:</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'> 149.1 x 70.8 x 7.7 mm<o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:4'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Procesor<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Tip:</span></b><span lang=EN-US
                          style='font-size:12.0pt;font-family:""Times New Roman"",serif;mso-fareast-font-family:
                          ""Times New Roman""'> Octa-core, HiSilicon Kirin 970, Mali-G72 MP12<br>
                          <b>Takt:</b> Quad-core 2.4 GHz Cortex-A73 &amp; quad-core 1.8 GHz Cortex-A53 <o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:5'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Baterija<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Vrsta:</span></b><span lang=EN-US
                          style='font-size:12.0pt;font-family:""Times New Roman"",serif;mso-fareast-font-family:
                          ""Times New Roman""'> Li-Ion (baterija nije zamenjiva bez asistencije servisa)<br>
                          <b>Kapacitet:</b> 3400 mAh<br>
                          <b>Režim razgovora:</b> do 20 h (3G)<br>
                          <b>Stand by režim:</b> do 585 h (3G)<o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:6'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Ostalo<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Ostalo:</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'> dual sim, vibracija, senzor
                          otisak prsta, digitalni kompas, akcelerometar, Gyroscope <o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:7'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Ekran<o:p></o:p></span></b></p>
                          </td>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Glavni<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Tip:</span></b><span lang=EN-US
                          style='font-size:12.0pt;font-family:""Times New Roman"",serif;mso-fareast-font-family:
                          ""Times New Roman""'> LTPS IPS LCD (5.8 inča) capacitive<br>
                          <b>Broj boja:</b> (24-bit) 16.777.216 boja<br>
                          <b>Rezolucija:</b> 1080x2240 piksela<br>
                          <b>Ostalo:</b> osetljiv na dodir, sposobnost dodira ekrana da registruje više
                          različitih pozicija, Emotion UI 8.1 <o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:8'>
                          <td width=""15%"" rowspan=2 valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Kamera<o:p></o:p></span></b></p>
                          </td>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Glavna<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Orijentacija sočiva:</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'> sa zadnje strane<br>
                          <b>Broj piksela senzora:</b> Dual kamera 12 MP (f/1.8, OIS) + 20 MP (f/1.6,
                          27mm)<br>
                          <b>Rezolucija fotografija:</b> 4096x3080 piksela<br>
                          <b>Rezolucija videa:</b> 2160p@30fps, 1080p@60fps, 720p@960fps<br>
                          <b>Ostalo:</b> video zapis, laser i phase detectzija autofokus, LED blic, digitalni
                          zoom, automatsko označavanje lokacije, detekcija lica, HDR, panorama mod <o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:9'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Pomoćna<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Orijentacija sočiva:</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'> sa prednje strane<br>
                          <b>Broj piksela senzora:</b> 24 megapiksela<br>
                          <b>Rezolucija videa:</b> 1080p@30fps<br>
                          <b>Ostalo:</b> f/2.0 <o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:10'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Zvuk<o:p></o:p></span></b></p>
                          </td>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Reprodukcija<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Zvučnici:</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'> mono zvučnik sa ugrađenim
                          pojačalom 24-bit/192kHz audio<br>
                          <b>Melodije:</b> polifone<br>
                          <b>Format melodija:</b> mp3, aac, aac+, eaac+, flac, wav, ogg, midi, amr<br>
                          <b>Ostalo:</b> spikerfon, specijalan mikrofon za smanjenje buke <o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:11'>
                          <td width=""15%"" rowspan=2 valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Memorija<o:p></o:p></span></b></p>
                          </td>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Interna<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Kapacitet:</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'> 64 GB (4 GB RAM)<o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:12'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Eksterna<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Formati:</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'> nema opciju za memorijsku karticu<br>
                          <b>Uz aparat:</b> ne ide kartica<o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:13'>
                          <td width=""15%"" rowspan=3 valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Softver<o:p></o:p></span></b></p>
                          </td>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Operativni <br>
                          sistem<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Tip:</span></b><span lang=EN-US
                          style='font-size:12.0pt;font-family:""Times New Roman"",serif;mso-fareast-font-family:
                          ""Times New Roman""'> Android OS<br>
                          <b>Verzija:</b> v8.1 (Oreo)<br>
                          <b>Formati:</b> mpeg4, H.263, H.264, xvid, wmv <o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:14'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Java<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Profil:</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'> ne<br>
                          <b>Konfiguracija:</b> podržava isključivo Nano SIM karticu, čitač dokumenata,
                          NFC podrška <o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:15'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Funkcije<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Osnovne:</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'> kalkulator, kalendar, alarm,
                          digitalni sat, notes, podsetnik, štoperica<br>
                          <b>Napredne:</b> komandovanje glasom, pozivanje glasom, snimanje glasa <o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:16'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Komunikacija<o:p></o:p></span></b></p>
                          </td>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Udaljeno<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Prenos podataka:</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'> GSM (9,6 Kb/s), GPRS (115 Kb/s),
                          EDGE (236 Kb/s), HSDPA, LTE<br>
                          <b>WAP pretraživač:</b> HTML5<br>
                          <b>Email protokoli:</b> IMAP, POP3, SMTP, Microsoft Exchange<br>
                          <b>Ostalo:</b> SMS, MMS, Email, Push Mail, IM <o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:17;mso-yfti-lastrow:yes'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Povezivanje<o:p></o:p></span></b></p>
                          </td>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Podržane <br>
                          tehnologije<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>GPRS:</span></b><span lang=EN-US
                          style='font-size:12.0pt;font-family:""Times New Roman"",serif;mso-fareast-font-family:
                          ""Times New Roman""'> da<br>
                          <b>EDGE:</b> da<br>
                          <b>3G:</b> da, HSDPA, 42 Mbps; HSUPA, 5.76 Mbps; LTE, Cat6, 50 Mbps UL, 300
                          Mbps DL<br>
                          <b>WLAN:</b> da, Wi-Fi 802.11 a/b/g/n/ac, dual-band, Wi-Fi hotspot, Wi-Fi
                          Direct<br>
                          <b>Bluetooth:</b> da, v4.2 sa A2DP, EDR, LE<br>
                          <b>USB i spikerfon:</b> da, microUSB 3.1 (Type-C 1.0 Reversible), nema ulaz
                          3.5' audio<br>
                          <b>GPS:</b> da, sa A-GPS podrškom i GLONASS <o:p></o:p></span></p>
                          </td>
                         </tr>
                        </table>",
                            Discount = 0,
                            Identifier = new Guid("cb56ab55-3085-4721-8cd4-0eecc3b8fd06"),
                            Name = "Huawei P20 Dual SIM 64GB 4GB RAM",
                            Price = 309m,
                            Tags = "Phones;Huawei;P20;Dual-Sim;",
                            UpdatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 401, DateTimeKind.Local).AddTicks(6651)
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 401, DateTimeKind.Local).AddTicks(7166),
                            Description = "OPIS_TELEFONA",
                            Discount = 0,
                            Identifier = new Guid("27f6396c-8041-484a-9d73-50bc26bfa428"),
                            Name = "LG V50 ThinQ 5G 128GB 6GB RAM",
                            Price = 825m,
                            Tags = "Phones;LG;V50;ThinQ;",
                            UpdatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 401, DateTimeKind.Local).AddTicks(7172)
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 401, DateTimeKind.Local).AddTicks(7326),
                            Description = "OPIS_TELEFONA",
                            Discount = 0,
                            Identifier = new Guid("53cdf494-d911-4a62-bb18-7342a6c28f07"),
                            Name = "LG V40 ThinQ Dual SIM 128GB 6GB RAM",
                            Price = 425m,
                            Tags = "Phones;LG;V40;ThinQ;",
                            UpdatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 401, DateTimeKind.Local).AddTicks(7333)
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 401, DateTimeKind.Local).AddTicks(7482),
                            Description = "OPIS_TELEFONA",
                            Discount = 0,
                            Identifier = new Guid("48273312-daac-4601-85ee-0acd86116c14"),
                            Name = "Nokia 7.2 Dual SIM 128GB 6GB RAM",
                            Price = 319m,
                            Tags = "Phones;Nokia;7.2;Dual-Sim;",
                            UpdatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 401, DateTimeKind.Local).AddTicks(7488)
                        },
                        new
                        {
                            Id = 6,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 401, DateTimeKind.Local).AddTicks(7654),
                            Description = "OPIS_TELEFONA",
                            Discount = 0,
                            Identifier = new Guid("c98c4f2f-10a7-4bac-bfcc-f01db828d279"),
                            Name = "Nokia 6.2 Dual SIM 128GB 4GB RAM",
                            Price = 255m,
                            Tags = "Phones;Nokia;6.2;Dual-Sim;",
                            UpdatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 401, DateTimeKind.Local).AddTicks(7660)
                        },
                        new
                        {
                            Id = 7,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 401, DateTimeKind.Local).AddTicks(7995),
                            Description = "OPIS_TELEFONA",
                            Discount = 0,
                            Identifier = new Guid("96ab4857-d0ce-4d96-8bc0-6f0486330c79"),
                            Name = "Apple iPhone 11 Dual eSIM 64GB 4GB",
                            Price = 735m,
                            Tags = "Phones;Apple;iPhone;11;XI;Dual-Sim;",
                            UpdatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 401, DateTimeKind.Local).AddTicks(8001)
                        },
                        new
                        {
                            Id = 8,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 401, DateTimeKind.Local).AddTicks(8148),
                            Description = "OPIS_TELEFONA",
                            Discount = 0,
                            Identifier = new Guid("01d18ea0-27c9-47c6-9efd-2216373cdfb5"),
                            Name = "Apple iPhone X 64GB",
                            Price = 425m,
                            Tags = "Phones;Apple;iPhone;10;X;",
                            UpdatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 401, DateTimeKind.Local).AddTicks(8154)
                        },
                        new
                        {
                            Id = 9,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 401, DateTimeKind.Local).AddTicks(8324),
                            Description = "OPIS_TELEFONA",
                            Discount = 0,
                            Identifier = new Guid("d986239a-00bb-41b4-98ea-800bb8d67f9f"),
                            Name = "Samsung Galaxy Note 10 Lite Dual SIM 128GB 6GB RAM",
                            Price = 980m,
                            Tags = "Phones;Samsung;Galaxy;Note10;Dual-Sim;",
                            UpdatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 401, DateTimeKind.Local).AddTicks(8330)
                        },
                        new
                        {
                            Id = 10,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 401, DateTimeKind.Local).AddTicks(8490),
                            Description = "OPIS_TELEFONA",
                            Discount = 0,
                            Identifier = new Guid("c41319c8-5ed6-4d10-b78b-3eadda55f22b"),
                            Name = "Samsung Galaxy A50 Dual SIM 128GB 4GB RAM",
                            Price = 300m,
                            Tags = "Phones;Samsung;Galaxy;A50;Dual-Sim;",
                            UpdatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 401, DateTimeKind.Local).AddTicks(8496)
                        },
                        new
                        {
                            Id = 11,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 401, DateTimeKind.Local).AddTicks(8645),
                            Description = "OPIS_TELEFONA",
                            Discount = 0,
                            Identifier = new Guid("17b80d04-1f35-420b-b6d7-876af4d56fef"),
                            Name = "Xiaomi Mi Note 10 Pro Dual SIM 256GB 8GB RAM",
                            Price = 510m,
                            Tags = "Phones;Xiaomi;Mi;Note10;Pro;Dual-Sim;",
                            UpdatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 401, DateTimeKind.Local).AddTicks(8652)
                        },
                        new
                        {
                            Id = 12,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 401, DateTimeKind.Local).AddTicks(8798),
                            Description = "OPIS_TELEFONA",
                            Discount = 0,
                            Identifier = new Guid("db2dd368-c7a3-439a-96ac-046c65ec3b3b"),
                            Name = "Xiaomi Mi 9 Lite Dual SIM 128GB 6GB RAM",
                            Price = 350m,
                            Tags = "Phones;Xiaomi;Mi;9;Lite;Dual-Sim;",
                            UpdatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 401, DateTimeKind.Local).AddTicks(8804)
                        });
                });

            modelBuilder.Entity("Domain.Products.ProductPhoto", b =>
                {
                    b.Property<int?>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("text");

                    b.Property<bool>("MainPhoto")
                        .HasColumnType("boolean");

                    b.HasKey("ProductId", "PhotoPath");

                    b.ToTable("ProductPhotos");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            PhotoPath = "/photos/phones/Huawei/Huawei_P30_Lite_Blue_Front.jpg",
                            MainPhoto = true
                        },
                        new
                        {
                            ProductId = 2,
                            PhotoPath = "/photos/phones/Huawei/Huawei_P20_Twilight_Front.jpg",
                            MainPhoto = true
                        },
                        new
                        {
                            ProductId = 3,
                            PhotoPath = "/photos/phones/LG/LG_V50_ThinQ_5G_Black_Front.jpg",
                            MainPhoto = true
                        },
                        new
                        {
                            ProductId = 4,
                            PhotoPath = "/photos/phones/LG/LG_V40_Thinq_Platinum_Grey_Front.jpg",
                            MainPhoto = true
                        },
                        new
                        {
                            ProductId = 5,
                            PhotoPath = "/photos/phones/Nokia/Nokia_7-2_Green_Front.jpg",
                            MainPhoto = true
                        },
                        new
                        {
                            ProductId = 6,
                            PhotoPath = "/photos/phones/Nokia/Nokia_6-2_Black_Front.jpg",
                            MainPhoto = true
                        },
                        new
                        {
                            ProductId = 7,
                            PhotoPath = "/photos/phones/Apple/Apple_iPhone_11_Yellow_Front.jpg",
                            MainPhoto = true
                        },
                        new
                        {
                            ProductId = 8,
                            PhotoPath = "/photos/phones/Apple/Apple_iPhone_X_Space_Grey_Front.jpg",
                            MainPhoto = true
                        },
                        new
                        {
                            ProductId = 9,
                            PhotoPath = "/photos/phones/Samsung/Samsung_Galaxy_Note_10_Lite_Aura_Black_Front.jpg",
                            MainPhoto = true
                        },
                        new
                        {
                            ProductId = 10,
                            PhotoPath = "/photos/phones/Samsung/Samsung_Galaxy_A50_Black_Front.jpg",
                            MainPhoto = true
                        },
                        new
                        {
                            ProductId = 11,
                            PhotoPath = "/photos/phones/Xiaomi/Xiaomi_Mi_Note-Pro_10_Green_Front.jpg",
                            MainPhoto = true
                        },
                        new
                        {
                            ProductId = 12,
                            PhotoPath = "/photos/phones/Xiaomi/Xiaomi_Mi_9_Lite_White_Front.jpg",
                            MainPhoto = true
                        });
                });

            modelBuilder.Entity("Domain.Products.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("Identifier")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("ParentProductTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParentProductTypeId");

                    b.ToTable("ProductTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 397, DateTimeKind.Local).AddTicks(2741),
                            Description = "Phones",
                            Identifier = new Guid("c94bd74a-e77c-4c78-b851-7e1ae7b9ddde"),
                            Name = "Phones",
                            UpdatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 397, DateTimeKind.Local).AddTicks(3716)
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 397, DateTimeKind.Local).AddTicks(4831),
                            Description = "Masks",
                            Identifier = new Guid("2e84f6ba-5f3f-4bad-8bc7-661007a162ea"),
                            Name = "Masks",
                            UpdatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 397, DateTimeKind.Local).AddTicks(4862)
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 397, DateTimeKind.Local).AddTicks(4899),
                            Description = "Chargers",
                            Identifier = new Guid("08932bd1-04f2-49c6-a2f3-b1dbf95c0f4b"),
                            Name = "Chargers",
                            UpdatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 397, DateTimeKind.Local).AddTicks(4906)
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 397, DateTimeKind.Local).AddTicks(4927),
                            Description = "Earphones",
                            Identifier = new Guid("8597cd5a-3467-49b5-ba04-f700ea8c8a5d"),
                            Name = "Earphones",
                            UpdatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 397, DateTimeKind.Local).AddTicks(4933)
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 397, DateTimeKind.Local).AddTicks(4954),
                            Description = "Batteries",
                            Identifier = new Guid("667c8c61-3a33-4b49-b2a0-d41481eb93cb"),
                            Name = "Batteries",
                            UpdatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 397, DateTimeKind.Local).AddTicks(4960)
                        },
                        new
                        {
                            Id = 6,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 397, DateTimeKind.Local).AddTicks(5936),
                            Description = "Huawei",
                            Identifier = new Guid("fdb6e79e-d7a0-4e77-8d23-8e0aed2e0a29"),
                            Name = "Huawei",
                            ParentProductTypeId = 1,
                            UpdatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 397, DateTimeKind.Local).AddTicks(5959)
                        },
                        new
                        {
                            Id = 7,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 397, DateTimeKind.Local).AddTicks(6009),
                            Description = "LG",
                            Identifier = new Guid("fe8aa944-f9e8-4da5-b211-c6c7d8fd6ad5"),
                            Name = "LG",
                            ParentProductTypeId = 1,
                            UpdatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 397, DateTimeKind.Local).AddTicks(6016)
                        },
                        new
                        {
                            Id = 8,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 397, DateTimeKind.Local).AddTicks(6039),
                            Description = "Nokia",
                            Identifier = new Guid("05bb8b23-eb60-4a5b-9259-fddb7128fce0"),
                            Name = "Nokia",
                            ParentProductTypeId = 1,
                            UpdatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 397, DateTimeKind.Local).AddTicks(6045)
                        },
                        new
                        {
                            Id = 9,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 397, DateTimeKind.Local).AddTicks(6067),
                            Description = "Apple",
                            Identifier = new Guid("9ac869dc-10f5-4b78-8d76-fa6239ef7ae9"),
                            Name = "Apple",
                            ParentProductTypeId = 1,
                            UpdatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 397, DateTimeKind.Local).AddTicks(6073)
                        },
                        new
                        {
                            Id = 10,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 397, DateTimeKind.Local).AddTicks(6095),
                            Description = "Samsung",
                            Identifier = new Guid("abddd9b0-058d-4863-a285-2f0e3c869be8"),
                            Name = "Samsung",
                            ParentProductTypeId = 1,
                            UpdatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 397, DateTimeKind.Local).AddTicks(6101)
                        },
                        new
                        {
                            Id = 11,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 397, DateTimeKind.Local).AddTicks(6122),
                            Description = "Xiaomi",
                            Identifier = new Guid("a36f9ebf-d205-4e44-a51d-e183e2089a5d"),
                            Name = "Xiaomi",
                            ParentProductTypeId = 1,
                            UpdatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 397, DateTimeKind.Local).AddTicks(6129)
                        },
                        new
                        {
                            Id = 12,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 397, DateTimeKind.Local).AddTicks(6150),
                            Description = "Huawei",
                            Identifier = new Guid("396102f2-757c-4a15-b7c3-98f8aa61e0e2"),
                            Name = "Huawei",
                            ParentProductTypeId = 2,
                            UpdatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 397, DateTimeKind.Local).AddTicks(6156)
                        },
                        new
                        {
                            Id = 13,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 397, DateTimeKind.Local).AddTicks(6266),
                            Description = "LG",
                            Identifier = new Guid("8ed3d7ec-c8cd-4a2c-bb75-211779a00dde"),
                            Name = "LG",
                            ParentProductTypeId = 2,
                            UpdatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 397, DateTimeKind.Local).AddTicks(6273)
                        },
                        new
                        {
                            Id = 14,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 397, DateTimeKind.Local).AddTicks(6302),
                            Description = "Nokia",
                            Identifier = new Guid("9eefcccf-66eb-4494-a694-49d9c2f29bf7"),
                            Name = "Nokia",
                            ParentProductTypeId = 2,
                            UpdatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 397, DateTimeKind.Local).AddTicks(6309)
                        },
                        new
                        {
                            Id = 15,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 397, DateTimeKind.Local).AddTicks(6330),
                            Description = "Apple",
                            Identifier = new Guid("6424a195-276e-4463-9915-1c1c692df6e7"),
                            Name = "Apple",
                            ParentProductTypeId = 2,
                            UpdatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 397, DateTimeKind.Local).AddTicks(6336)
                        },
                        new
                        {
                            Id = 16,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 397, DateTimeKind.Local).AddTicks(6357),
                            Description = "Samsung",
                            Identifier = new Guid("6573cc2d-0bc4-4ea8-ae36-d1bc9ee696d8"),
                            Name = "Samsung",
                            ParentProductTypeId = 2,
                            UpdatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 397, DateTimeKind.Local).AddTicks(6364)
                        },
                        new
                        {
                            Id = 17,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 397, DateTimeKind.Local).AddTicks(6385),
                            Description = "Xiaomi",
                            Identifier = new Guid("cf8ac7c1-5050-4f9d-8e59-fcd96fd1a281"),
                            Name = "Xiaomi",
                            ParentProductTypeId = 2,
                            UpdatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 397, DateTimeKind.Local).AddTicks(6391)
                        },
                        new
                        {
                            Id = 18,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 397, DateTimeKind.Local).AddTicks(6412),
                            Description = "Huawei",
                            Identifier = new Guid("769d012d-9858-438d-8b1a-64c5e239a4b6"),
                            Name = "Huawei",
                            ParentProductTypeId = 4,
                            UpdatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 397, DateTimeKind.Local).AddTicks(6418)
                        },
                        new
                        {
                            Id = 19,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 397, DateTimeKind.Local).AddTicks(6439),
                            Description = "LG",
                            Identifier = new Guid("786eca4b-51b7-4f09-acb5-8f4ea981d835"),
                            Name = "LG",
                            ParentProductTypeId = 4,
                            UpdatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 397, DateTimeKind.Local).AddTicks(6446)
                        },
                        new
                        {
                            Id = 20,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 397, DateTimeKind.Local).AddTicks(6467),
                            Description = "Nokia",
                            Identifier = new Guid("ec32efed-05f8-4fce-9d99-caf73fae04e0"),
                            Name = "Nokia",
                            ParentProductTypeId = 4,
                            UpdatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 397, DateTimeKind.Local).AddTicks(6473)
                        },
                        new
                        {
                            Id = 21,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 397, DateTimeKind.Local).AddTicks(6494),
                            Description = "Apple",
                            Identifier = new Guid("6a0d07d0-ee5b-4c71-8a94-9a000ed70a06"),
                            Name = "Apple",
                            ParentProductTypeId = 4,
                            UpdatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 397, DateTimeKind.Local).AddTicks(6500)
                        },
                        new
                        {
                            Id = 22,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 397, DateTimeKind.Local).AddTicks(6527),
                            Description = "Samsung",
                            Identifier = new Guid("ec4b5ecb-16a7-4a56-bd50-7bc035570ae2"),
                            Name = "Samsung",
                            ParentProductTypeId = 4,
                            UpdatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 397, DateTimeKind.Local).AddTicks(6533)
                        },
                        new
                        {
                            Id = 23,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 397, DateTimeKind.Local).AddTicks(6554),
                            Description = "Xiaomi",
                            Identifier = new Guid("416bbdc2-b302-4f64-a312-f125f470b535"),
                            Name = "Xiaomi",
                            ParentProductTypeId = 4,
                            UpdatedAt = new DateTime(2020, 2, 27, 15, 40, 40, 397, DateTimeKind.Local).AddTicks(6561)
                        });
                });

            modelBuilder.Entity("Domain.Products.Product_ProductType", b =>
                {
                    b.Property<int?>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProductTypeId")
                        .HasColumnType("integer");

                    b.HasKey("ProductId", "ProductTypeId");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("Product_ProductType");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            ProductTypeId = 6
                        },
                        new
                        {
                            ProductId = 2,
                            ProductTypeId = 6
                        },
                        new
                        {
                            ProductId = 3,
                            ProductTypeId = 7
                        },
                        new
                        {
                            ProductId = 4,
                            ProductTypeId = 7
                        },
                        new
                        {
                            ProductId = 5,
                            ProductTypeId = 8
                        },
                        new
                        {
                            ProductId = 6,
                            ProductTypeId = 8
                        },
                        new
                        {
                            ProductId = 7,
                            ProductTypeId = 9
                        },
                        new
                        {
                            ProductId = 8,
                            ProductTypeId = 9
                        },
                        new
                        {
                            ProductId = 9,
                            ProductTypeId = 10
                        },
                        new
                        {
                            ProductId = 10,
                            ProductTypeId = 9
                        },
                        new
                        {
                            ProductId = 11,
                            ProductTypeId = 11
                        },
                        new
                        {
                            ProductId = 12,
                            ProductTypeId = 11
                        });
                });

            modelBuilder.Entity("Domain.Products.ProductPhoto", b =>
                {
                    b.HasOne("Domain.Products.Product", "Product")
                        .WithMany("ProductPhotos")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Products.ProductType", b =>
                {
                    b.HasOne("Domain.Products.ProductType", "ParentProductType")
                        .WithMany("SubTypes")
                        .HasForeignKey("ParentProductTypeId");
                });

            modelBuilder.Entity("Domain.Products.Product_ProductType", b =>
                {
                    b.HasOne("Domain.Products.Product", "Product")
                        .WithMany("Product_ProductTypes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Products.ProductType", "ProductType")
                        .WithMany("Product_ProductTypes")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
