// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Repository.Context;

namespace Repository.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200227125216_IzmenaSeed")]
    partial class IzmenaSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Domain.Products.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Discount")
                        .HasColumnType("integer");

                    b.Property<Guid>("Identifier")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Tags")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 13, 52, 15, 401, DateTimeKind.Local).AddTicks(8247),
                            Description = @"
                        <table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 width=""100%""
                         style='width:100.0%;mso-cellspacing:0cm;mso-yfti-tbllook:1184;mso-padding-alt:
                         0cm 0cm 0cm 0cm'>
                         <tr style='mso-yfti-irow:0;mso-yfti-firstrow:yes'>
                          <td width=""15%"" rowspan=2 valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Model<o:p></o:p></span></b></p>
                          </td>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Naziv<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Huawei P30 Lite Dual SIM 128GB 4GB
                          RAM (plava)</span></b><span lang=EN-US style='font-size:12.0pt;font-family:
                          ""Times New Roman"",serif;mso-fareast-font-family:""Times New Roman""'><o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:1'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Poznat kao<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>MAR-LX1A</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'><o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:2'>
                          <td width=""15%"" rowspan=5 valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Osnovno<o:p></o:p></span></b></p>
                          </td>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Market<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Mreže:</span></b><span lang=EN-US
                          style='font-size:12.0pt;font-family:""Times New Roman"",serif;mso-fareast-font-family:
                          ""Times New Roman""'> 850Mhz, 900Mhz, 1800Mhz, 1900Mhz, 2100Mhz, 2600Mhz,
                          HSDPA, LTE<o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:3'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Kućište<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Dimenzije:</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'> 152.9 x 72.7 x 7.4 mm<o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:4'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Procesor<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Tip:</span></b><span lang=EN-US
                          style='font-size:12.0pt;font-family:""Times New Roman"",serif;mso-fareast-font-family:
                          ""Times New Roman""'> Octa-core, Hisilicon Kirin 710, Mali-G51 MP4<br>
                          <b>Takt:</b> Quad-core 2.2 GHz Cortex-A73 &amp; Quad-core 1.7 GHz Cortex-A53<o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:5'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Baterija<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Vrsta:</span></b><span lang=EN-US
                          style='font-size:12.0pt;font-family:""Times New Roman"",serif;mso-fareast-font-family:
                          ""Times New Roman""'> Li-Po (baterija nije zamenjiva bez asistencije servisa)<br>
                          <b>Kapacitet:</b> 3340 mAh<br>
                          <b>Režim razgovora:</b> do 22 h (3G)<br>
                          <b>Stand by režim:</b> do 595 h (3G)<o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:6'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Ostalo<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Ostalo:</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'> dual sim, vibracija, senzor
                          otisak prsta, digitalni kompas, akcelerometar, Gyroscope<o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:7'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Ekran<o:p></o:p></span></b></p>
                          </td>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Glavni<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Tip:</span></b><span lang=EN-US
                          style='font-size:12.0pt;font-family:""Times New Roman"",serif;mso-fareast-font-family:
                          ""Times New Roman""'> LTPS IPS LCD (6.15 inča) capacitive<br>
                          <b>Broj boja:</b> (24-bit) 16.777.216 boja<br>
                          <b>Rezolucija:</b> 1080x2312 piksela<br>
                          <b>Ostalo:</b> osetljiv na dodir, sposobnost dodira ekrana da registruje više
                          različitih pozicija, EMUI 9.0<o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:8'>
                          <td width=""15%"" rowspan=2 valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Kamera<o:p></o:p></span></b></p>
                          </td>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Glavna<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Orijentacija sočiva:</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'> sa zadnje strane<br>
                          <b>Broj piksela senzora:</b> 48 MP (f1.8, wide, PDAF) + 8 MP (13mm ultrawide)
                          + 2 MP (f/2.4, depth sensor)<br>
                          <b>Rezolucija fotografija:</b> 5290x4512 piksela<br>
                          <b>Rezolucija videa:</b> 1080p@30fps (gyro-EIS)<br>
                          <b>Ostalo:</b> video zapis, LED blic, digitalni zoom, automatsko označavanje
                          lokacije, detekcija lica, HDR, panorama mod<o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:9'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Pomoćna<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Orijentacija sočiva:</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'> sa prednje strane<br>
                          <b>Broj piksela senzora:</b> 24 megapiksela<br>
                          <b>Rezolucija videa:</b> 1080p@30fps<br>
                          <b>Ostalo:</b> f/2.0, HDR<o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:10'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Zvuk<o:p></o:p></span></b></p>
                          </td>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Reprodukcija<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Zvučnici:</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'> mono zvučnik sa ugrađenim
                          pojačalom<br>
                          <b>Melodije:</b> polifone<br>
                          <b>Format melodija:</b> mp3, aac, aac+, eaac+, flac, wav, ogg, midi, amr<br>
                          <b>Ostalo:</b> spikerfon, specijalan mikrofon za smanjenje buke<o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:11'>
                          <td width=""15%"" rowspan=2 valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Memorija<o:p></o:p></span></b></p>
                          </td>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Interna<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Kapacitet:</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'> 128 GB (4 GB RAM)<o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:12'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Eksterna<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Formati:</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'> microSD (Trans Flash),Maximalno
                          podržano : 512 GB (shared SIM slot)<br>
                          <b>Uz aparat:</b> ne ide kartica<o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:13'>
                          <td width=""15%"" rowspan=3 valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Softver<o:p></o:p></span></b></p>
                          </td>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Operativni <br>
                          sistem<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Tip:</span></b><span lang=EN-US
                          style='font-size:12.0pt;font-family:""Times New Roman"",serif;mso-fareast-font-family:
                          ""Times New Roman""'> Android OS<br>
                          <b>Verzija:</b> v9.0 (Pie)<br>
                          <b>Formati:</b> mpeg4, H.263, H.264, xvid, wmv<o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:14'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Java<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Profil:</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'> ne<br>
                          <b>Konfiguracija:</b> podržava isključivo Nano SIM karticu, čitač dokumenata<o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:15'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Funkcije<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Osnovne:</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'> kalkulator, kalendar, alarm,
                          digitalni sat, notes, podsetnik, štoperica<br>
                          <b>Napredne:</b> komandovanje glasom, pozivanje glasom, snimanje glasa<o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:16'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Komunikacija<o:p></o:p></span></b></p>
                          </td>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Udaljeno<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Prenos podataka:</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'> GSM (9,6 Kb/s), GPRS (115 Kb/s),
                          EDGE (236 Kb/s), HSDPA, LTE<br>
                          <b>WAP pretraživač:</b> HTML5<br>
                          <b>Email protokoli:</b> IMAP, POP3, SMTP, Microsoft Exchange<br>
                          <b>Ostalo:</b> SMS, MMS, Email, Push Mail, IM<o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:17;mso-yfti-lastrow:yes'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Povezivanje<o:p></o:p></span></b></p>
                          </td>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Podržane <br>
                          tehnologije<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>GPRS:</span></b><span lang=EN-US
                          style='font-size:12.0pt;font-family:""Times New Roman"",serif;mso-fareast-font-family:
                          ""Times New Roman""'> da<br>
                          <b>EDGE:</b> da<br>
                          <b>3G:</b> da, HSDPA, 42 Mbps; HSUPA, 5.76 Mbps; LTE, Cat6, 50 Mbps UL, 300
                          Mbps DL<br>
                          <b>WLAN:</b> da, Wi-Fi 802.11 a/b/g/n/ac, dual-band, Wi-Fi hotspot, Wi-Fi
                          Direct<br>
                          <b>Bluetooth:</b> da, v4.2 sa A2DP, LE, aptX HD<br>
                          <b>USB i spikerfon:</b> da, microUSB v2.0 (Type-C 1.0 reversible connector),
                          3.5' audio<br>
                          <b>GPS:</b> da, sa A-GPS podrškom i GLONASS, BDS<o:p></o:p></span></p>
                          </td>
                         </tr>
                        </table>",
                            Discount = 0,
                            Identifier = new Guid("722de11b-bdf9-4964-92d7-ad3ff467bd33"),
                            Name = "Huawei P30 Lite Dual SIM 128GB 4GB RAM",
                            Price = 500m,
                            Tags = "Phones;Huawei;P30;Lite;",
                            UpdatedAt = new DateTime(2020, 2, 27, 13, 52, 15, 401, DateTimeKind.Local).AddTicks(8257)
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 13, 52, 15, 403, DateTimeKind.Local).AddTicks(9860),
                            Description = @"
                        <table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 width=""100%""
                         style='width:100.0%;mso-cellspacing:0cm;mso-yfti-tbllook:1184;mso-padding-alt:
                         0cm 0cm 0cm 0cm'>
                         <tr style='mso-yfti-irow:0;mso-yfti-firstrow:yes'>
                          <td width=""15%"" rowspan=2 valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Model<o:p></o:p></span></b></p>
                          </td>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Naziv<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Huawei P20 Dual SIM 64GB 4GB RAM
                          (twilight plava)</span></b><span lang=EN-US style='font-size:12.0pt;
                          font-family:""Times New Roman"",serif;mso-fareast-font-family:""Times New Roman""'><o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:1'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Poznat kao<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>EML-L29, EML-L09</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'><o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:2'>
                          <td width=""15%"" rowspan=5 valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Osnovno<o:p></o:p></span></b></p>
                          </td>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Market<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Mreže:</span></b><span lang=EN-US
                          style='font-size:12.0pt;font-family:""Times New Roman"",serif;mso-fareast-font-family:
                          ""Times New Roman""'> 850Mhz, 900Mhz, 1800Mhz, 1900Mhz, 2100Mhz, 2600Mhz,
                          HSDPA, LTE<o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:3'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Kućište<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Dimenzije:</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'> 149.1 x 70.8 x 7.7 mm<o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:4'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Procesor<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Tip:</span></b><span lang=EN-US
                          style='font-size:12.0pt;font-family:""Times New Roman"",serif;mso-fareast-font-family:
                          ""Times New Roman""'> Octa-core, HiSilicon Kirin 970, Mali-G72 MP12<br>
                          <b>Takt:</b> Quad-core 2.4 GHz Cortex-A73 &amp; quad-core 1.8 GHz Cortex-A53 <o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:5'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Baterija<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Vrsta:</span></b><span lang=EN-US
                          style='font-size:12.0pt;font-family:""Times New Roman"",serif;mso-fareast-font-family:
                          ""Times New Roman""'> Li-Ion (baterija nije zamenjiva bez asistencije servisa)<br>
                          <b>Kapacitet:</b> 3400 mAh<br>
                          <b>Režim razgovora:</b> do 20 h (3G)<br>
                          <b>Stand by režim:</b> do 585 h (3G)<o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:6'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Ostalo<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Ostalo:</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'> dual sim, vibracija, senzor
                          otisak prsta, digitalni kompas, akcelerometar, Gyroscope <o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:7'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Ekran<o:p></o:p></span></b></p>
                          </td>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Glavni<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Tip:</span></b><span lang=EN-US
                          style='font-size:12.0pt;font-family:""Times New Roman"",serif;mso-fareast-font-family:
                          ""Times New Roman""'> LTPS IPS LCD (5.8 inča) capacitive<br>
                          <b>Broj boja:</b> (24-bit) 16.777.216 boja<br>
                          <b>Rezolucija:</b> 1080x2240 piksela<br>
                          <b>Ostalo:</b> osetljiv na dodir, sposobnost dodira ekrana da registruje više
                          različitih pozicija, Emotion UI 8.1 <o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:8'>
                          <td width=""15%"" rowspan=2 valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Kamera<o:p></o:p></span></b></p>
                          </td>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Glavna<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Orijentacija sočiva:</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'> sa zadnje strane<br>
                          <b>Broj piksela senzora:</b> Dual kamera 12 MP (f/1.8, OIS) + 20 MP (f/1.6,
                          27mm)<br>
                          <b>Rezolucija fotografija:</b> 4096x3080 piksela<br>
                          <b>Rezolucija videa:</b> 2160p@30fps, 1080p@60fps, 720p@960fps<br>
                          <b>Ostalo:</b> video zapis, laser i phase detectzija autofokus, LED blic, digitalni
                          zoom, automatsko označavanje lokacije, detekcija lica, HDR, panorama mod <o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:9'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Pomoćna<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Orijentacija sočiva:</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'> sa prednje strane<br>
                          <b>Broj piksela senzora:</b> 24 megapiksela<br>
                          <b>Rezolucija videa:</b> 1080p@30fps<br>
                          <b>Ostalo:</b> f/2.0 <o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:10'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Zvuk<o:p></o:p></span></b></p>
                          </td>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Reprodukcija<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Zvučnici:</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'> mono zvučnik sa ugrađenim
                          pojačalom 24-bit/192kHz audio<br>
                          <b>Melodije:</b> polifone<br>
                          <b>Format melodija:</b> mp3, aac, aac+, eaac+, flac, wav, ogg, midi, amr<br>
                          <b>Ostalo:</b> spikerfon, specijalan mikrofon za smanjenje buke <o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:11'>
                          <td width=""15%"" rowspan=2 valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Memorija<o:p></o:p></span></b></p>
                          </td>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Interna<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Kapacitet:</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'> 64 GB (4 GB RAM)<o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:12'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Eksterna<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Formati:</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'> nema opciju za memorijsku karticu<br>
                          <b>Uz aparat:</b> ne ide kartica<o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:13'>
                          <td width=""15%"" rowspan=3 valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Softver<o:p></o:p></span></b></p>
                          </td>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Operativni <br>
                          sistem<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Tip:</span></b><span lang=EN-US
                          style='font-size:12.0pt;font-family:""Times New Roman"",serif;mso-fareast-font-family:
                          ""Times New Roman""'> Android OS<br>
                          <b>Verzija:</b> v8.1 (Oreo)<br>
                          <b>Formati:</b> mpeg4, H.263, H.264, xvid, wmv <o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:14'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Java<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Profil:</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'> ne<br>
                          <b>Konfiguracija:</b> podržava isključivo Nano SIM karticu, čitač dokumenata,
                          NFC podrška <o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:15'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Funkcije<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Osnovne:</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'> kalkulator, kalendar, alarm,
                          digitalni sat, notes, podsetnik, štoperica<br>
                          <b>Napredne:</b> komandovanje glasom, pozivanje glasom, snimanje glasa <o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:16'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Komunikacija<o:p></o:p></span></b></p>
                          </td>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Udaljeno<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Prenos podataka:</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'> GSM (9,6 Kb/s), GPRS (115 Kb/s),
                          EDGE (236 Kb/s), HSDPA, LTE<br>
                          <b>WAP pretraživač:</b> HTML5<br>
                          <b>Email protokoli:</b> IMAP, POP3, SMTP, Microsoft Exchange<br>
                          <b>Ostalo:</b> SMS, MMS, Email, Push Mail, IM <o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:17;mso-yfti-lastrow:yes'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Povezivanje<o:p></o:p></span></b></p>
                          </td>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Podržane <br>
                          tehnologije<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>GPRS:</span></b><span lang=EN-US
                          style='font-size:12.0pt;font-family:""Times New Roman"",serif;mso-fareast-font-family:
                          ""Times New Roman""'> da<br>
                          <b>EDGE:</b> da<br>
                          <b>3G:</b> da, HSDPA, 42 Mbps; HSUPA, 5.76 Mbps; LTE, Cat6, 50 Mbps UL, 300
                          Mbps DL<br>
                          <b>WLAN:</b> da, Wi-Fi 802.11 a/b/g/n/ac, dual-band, Wi-Fi hotspot, Wi-Fi
                          Direct<br>
                          <b>Bluetooth:</b> da, v4.2 sa A2DP, EDR, LE<br>
                          <b>USB i spikerfon:</b> da, microUSB 3.1 (Type-C 1.0 Reversible), nema ulaz
                          3.5' audio<br>
                          <b>GPS:</b> da, sa A-GPS podrškom i GLONASS <o:p></o:p></span></p>
                          </td>
                         </tr>
                        </table>",
                            Discount = 0,
                            Identifier = new Guid("04f30d76-22a1-4148-84c8-6f9739d37f5b"),
                            Name = "Huawei P20 Dual SIM 64GB 4GB RAM",
                            Price = 309m,
                            Tags = "Phones;Huawei;P20;Dual-Sim;",
                            UpdatedAt = new DateTime(2020, 2, 27, 13, 52, 15, 403, DateTimeKind.Local).AddTicks(9871)
                        });
                });

            modelBuilder.Entity("Domain.Products.ProductPhoto", b =>
                {
                    b.Property<int?>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("text");

                    b.Property<bool>("MainPhoto")
                        .HasColumnType("boolean");

                    b.HasKey("ProductId", "PhotoPath");

                    b.ToTable("ProductPhotos");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            PhotoPath = "/photos/phones/huawei/Huawei_P30_Lite_Blue_Front.jpg",
                            MainPhoto = true
                        },
                        new
                        {
                            ProductId = 2,
                            PhotoPath = "/photos/phones/huawei/Huawei_P20_Twilight_Front.jpg",
                            MainPhoto = true
                        });
                });

            modelBuilder.Entity("Domain.Products.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("Identifier")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("ParentProductTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParentProductTypeId");

                    b.ToTable("ProductTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 13, 52, 15, 396, DateTimeKind.Local).AddTicks(9519),
                            Description = "Phones",
                            Identifier = new Guid("17a3cc06-db02-4554-80c4-6c1125018145"),
                            Name = "Phones",
                            UpdatedAt = new DateTime(2020, 2, 27, 13, 52, 15, 397, DateTimeKind.Local).AddTicks(894)
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 13, 52, 15, 397, DateTimeKind.Local).AddTicks(2443),
                            Description = "Masks",
                            Identifier = new Guid("80ae22ae-7cfc-4af8-add4-ddeecff0ec90"),
                            Name = "Masks",
                            UpdatedAt = new DateTime(2020, 2, 27, 13, 52, 15, 397, DateTimeKind.Local).AddTicks(2485)
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 13, 52, 15, 397, DateTimeKind.Local).AddTicks(2533),
                            Description = "Chargers",
                            Identifier = new Guid("b4483d0b-4ae6-46a1-afcc-840b255a0a77"),
                            Name = "Chargers",
                            UpdatedAt = new DateTime(2020, 2, 27, 13, 52, 15, 397, DateTimeKind.Local).AddTicks(2542)
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 13, 52, 15, 397, DateTimeKind.Local).AddTicks(2570),
                            Description = "Earphones",
                            Identifier = new Guid("161dbf0f-0993-4d9d-9eaf-9e5c59e7dda8"),
                            Name = "Earphones",
                            UpdatedAt = new DateTime(2020, 2, 27, 13, 52, 15, 397, DateTimeKind.Local).AddTicks(2578)
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 13, 52, 15, 397, DateTimeKind.Local).AddTicks(2606),
                            Description = "Batteries",
                            Identifier = new Guid("7e344281-6dc5-48ca-9dc6-4cfad92ed496"),
                            Name = "Batteries",
                            UpdatedAt = new DateTime(2020, 2, 27, 13, 52, 15, 397, DateTimeKind.Local).AddTicks(2614)
                        },
                        new
                        {
                            Id = 6,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 13, 52, 15, 397, DateTimeKind.Local).AddTicks(4138),
                            Description = "Huawei",
                            Identifier = new Guid("8b44fa13-6800-4703-a65a-e032b070c02b"),
                            Name = "Huawei",
                            ParentProductTypeId = 1,
                            UpdatedAt = new DateTime(2020, 2, 27, 13, 52, 15, 397, DateTimeKind.Local).AddTicks(4181)
                        },
                        new
                        {
                            Id = 7,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 13, 52, 15, 397, DateTimeKind.Local).AddTicks(4252),
                            Description = "LG",
                            Identifier = new Guid("7272e440-7479-4713-8863-6b86d6b989e6"),
                            Name = "LG",
                            ParentProductTypeId = 1,
                            UpdatedAt = new DateTime(2020, 2, 27, 13, 52, 15, 397, DateTimeKind.Local).AddTicks(4262)
                        },
                        new
                        {
                            Id = 8,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 13, 52, 15, 397, DateTimeKind.Local).AddTicks(4319),
                            Description = "Nokia",
                            Identifier = new Guid("6c0dd947-2027-4a88-8350-177eb2b53a7c"),
                            Name = "Nokia",
                            ParentProductTypeId = 1,
                            UpdatedAt = new DateTime(2020, 2, 27, 13, 52, 15, 397, DateTimeKind.Local).AddTicks(4328)
                        },
                        new
                        {
                            Id = 9,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 13, 52, 15, 397, DateTimeKind.Local).AddTicks(4358),
                            Description = "Apple",
                            Identifier = new Guid("7c85a7c7-6cf6-4e49-b650-ecdcf5b9cf0d"),
                            Name = "Apple",
                            ParentProductTypeId = 1,
                            UpdatedAt = new DateTime(2020, 2, 27, 13, 52, 15, 397, DateTimeKind.Local).AddTicks(4368)
                        },
                        new
                        {
                            Id = 10,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 13, 52, 15, 397, DateTimeKind.Local).AddTicks(4401),
                            Description = "Samsung",
                            Identifier = new Guid("f0585af8-15de-4e9e-9782-e9c9ee37115d"),
                            Name = "Samsung",
                            ParentProductTypeId = 1,
                            UpdatedAt = new DateTime(2020, 2, 27, 13, 52, 15, 397, DateTimeKind.Local).AddTicks(4410)
                        },
                        new
                        {
                            Id = 11,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 13, 52, 15, 397, DateTimeKind.Local).AddTicks(4441),
                            Description = "Xiaomi",
                            Identifier = new Guid("3db8bdf6-48c7-4780-ab1e-d93005f60cb4"),
                            Name = "Xiaomi",
                            ParentProductTypeId = 1,
                            UpdatedAt = new DateTime(2020, 2, 27, 13, 52, 15, 397, DateTimeKind.Local).AddTicks(4451)
                        },
                        new
                        {
                            Id = 12,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 13, 52, 15, 397, DateTimeKind.Local).AddTicks(4479),
                            Description = "Huawei",
                            Identifier = new Guid("edfd1f39-5281-4e52-8a48-a0400e428162"),
                            Name = "Huawei",
                            ParentProductTypeId = 2,
                            UpdatedAt = new DateTime(2020, 2, 27, 13, 52, 15, 397, DateTimeKind.Local).AddTicks(4487)
                        },
                        new
                        {
                            Id = 13,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 13, 52, 15, 397, DateTimeKind.Local).AddTicks(4514),
                            Description = "LG",
                            Identifier = new Guid("53daaef2-b6ea-41cb-98b7-a4a1d3742696"),
                            Name = "LG",
                            ParentProductTypeId = 2,
                            UpdatedAt = new DateTime(2020, 2, 27, 13, 52, 15, 397, DateTimeKind.Local).AddTicks(4522)
                        },
                        new
                        {
                            Id = 14,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 13, 52, 15, 397, DateTimeKind.Local).AddTicks(4549),
                            Description = "Nokia",
                            Identifier = new Guid("b8843413-f756-47d0-9efe-b11f561364ab"),
                            Name = "Nokia",
                            ParentProductTypeId = 2,
                            UpdatedAt = new DateTime(2020, 2, 27, 13, 52, 15, 397, DateTimeKind.Local).AddTicks(4558)
                        },
                        new
                        {
                            Id = 15,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 13, 52, 15, 397, DateTimeKind.Local).AddTicks(4586),
                            Description = "Apple",
                            Identifier = new Guid("e1aa7e70-818c-431e-b6e7-c8b70599d6bc"),
                            Name = "Apple",
                            ParentProductTypeId = 2,
                            UpdatedAt = new DateTime(2020, 2, 27, 13, 52, 15, 397, DateTimeKind.Local).AddTicks(4594)
                        },
                        new
                        {
                            Id = 16,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 13, 52, 15, 397, DateTimeKind.Local).AddTicks(4631),
                            Description = "Samsung",
                            Identifier = new Guid("bc830573-d98c-4df7-9c4b-ac383a1bbcee"),
                            Name = "Samsung",
                            ParentProductTypeId = 2,
                            UpdatedAt = new DateTime(2020, 2, 27, 13, 52, 15, 397, DateTimeKind.Local).AddTicks(4639)
                        },
                        new
                        {
                            Id = 17,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 13, 52, 15, 397, DateTimeKind.Local).AddTicks(4667),
                            Description = "Xiaomi",
                            Identifier = new Guid("b41562a8-872e-48cf-a656-88aade6306bc"),
                            Name = "Xiaomi",
                            ParentProductTypeId = 2,
                            UpdatedAt = new DateTime(2020, 2, 27, 13, 52, 15, 397, DateTimeKind.Local).AddTicks(4675)
                        },
                        new
                        {
                            Id = 18,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 13, 52, 15, 397, DateTimeKind.Local).AddTicks(4703),
                            Description = "Huawei",
                            Identifier = new Guid("50c3342d-163f-41a0-8b8b-db33fbcad439"),
                            Name = "Huawei",
                            ParentProductTypeId = 4,
                            UpdatedAt = new DateTime(2020, 2, 27, 13, 52, 15, 397, DateTimeKind.Local).AddTicks(4711)
                        },
                        new
                        {
                            Id = 19,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 13, 52, 15, 397, DateTimeKind.Local).AddTicks(4738),
                            Description = "LG",
                            Identifier = new Guid("31fec34d-64d6-4cc9-a81e-ca6780c1b3ac"),
                            Name = "LG",
                            ParentProductTypeId = 4,
                            UpdatedAt = new DateTime(2020, 2, 27, 13, 52, 15, 397, DateTimeKind.Local).AddTicks(4747)
                        },
                        new
                        {
                            Id = 20,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 13, 52, 15, 397, DateTimeKind.Local).AddTicks(4775),
                            Description = "Nokia",
                            Identifier = new Guid("e2e6b02a-76bd-4258-a5c0-700bab2f3a65"),
                            Name = "Nokia",
                            ParentProductTypeId = 4,
                            UpdatedAt = new DateTime(2020, 2, 27, 13, 52, 15, 397, DateTimeKind.Local).AddTicks(4783)
                        },
                        new
                        {
                            Id = 21,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 13, 52, 15, 397, DateTimeKind.Local).AddTicks(4811),
                            Description = "Apple",
                            Identifier = new Guid("f7cb870d-7a96-4db7-af34-bb7688c20d74"),
                            Name = "Apple",
                            ParentProductTypeId = 4,
                            UpdatedAt = new DateTime(2020, 2, 27, 13, 52, 15, 397, DateTimeKind.Local).AddTicks(4819)
                        },
                        new
                        {
                            Id = 22,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 13, 52, 15, 397, DateTimeKind.Local).AddTicks(4846),
                            Description = "Samsung",
                            Identifier = new Guid("311a1e3a-d8c3-426d-b859-7f5d45d06e4f"),
                            Name = "Samsung",
                            ParentProductTypeId = 4,
                            UpdatedAt = new DateTime(2020, 2, 27, 13, 52, 15, 397, DateTimeKind.Local).AddTicks(4855)
                        },
                        new
                        {
                            Id = 23,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 13, 52, 15, 397, DateTimeKind.Local).AddTicks(4882),
                            Description = "Xiaomi",
                            Identifier = new Guid("098461f3-3e8f-4585-9859-d8f134045f4d"),
                            Name = "Xiaomi",
                            ParentProductTypeId = 4,
                            UpdatedAt = new DateTime(2020, 2, 27, 13, 52, 15, 397, DateTimeKind.Local).AddTicks(4890)
                        });
                });

            modelBuilder.Entity("Domain.Products.Product_ProductType", b =>
                {
                    b.Property<int?>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProductTypeId")
                        .HasColumnType("integer");

                    b.HasKey("ProductId", "ProductTypeId");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("Product_ProductType");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            ProductTypeId = 6
                        },
                        new
                        {
                            ProductId = 2,
                            ProductTypeId = 6
                        });
                });

            modelBuilder.Entity("Domain.Products.ProductPhoto", b =>
                {
                    b.HasOne("Domain.Products.Product", "Product")
                        .WithMany("ProductPhotos")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Products.ProductType", b =>
                {
                    b.HasOne("Domain.Products.ProductType", "ParentProductType")
                        .WithMany("SubTypes")
                        .HasForeignKey("ParentProductTypeId");
                });

            modelBuilder.Entity("Domain.Products.Product_ProductType", b =>
                {
                    b.HasOne("Domain.Products.Product", "Product")
                        .WithMany("Product_ProductTypes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Products.ProductType", "ProductType")
                        .WithMany("Product_ProductTypes")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
