// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Repository.Context;

namespace Repository.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200227131707_IzmenaSeed3")]
    partial class IzmenaSeed3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Domain.Products.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Discount")
                        .HasColumnType("integer");

                    b.Property<Guid>("Identifier")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Tags")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 979, DateTimeKind.Local).AddTicks(4646),
                            Description = @"
                        <table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 width=""100%""
                         style='width:100.0%;mso-cellspacing:0cm;mso-yfti-tbllook:1184;mso-padding-alt:
                         0cm 0cm 0cm 0cm'>
                         <tr style='mso-yfti-irow:0;mso-yfti-firstrow:yes'>
                          <td width=""15%"" rowspan=2 valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Model<o:p></o:p></span></b></p>
                          </td>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Naziv<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Huawei P30 Lite Dual SIM 128GB 4GB
                          RAM (plava)</span></b><span lang=EN-US style='font-size:12.0pt;font-family:
                          ""Times New Roman"",serif;mso-fareast-font-family:""Times New Roman""'><o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:1'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Poznat kao<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>MAR-LX1A</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'><o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:2'>
                          <td width=""15%"" rowspan=5 valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Osnovno<o:p></o:p></span></b></p>
                          </td>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Market<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Mreže:</span></b><span lang=EN-US
                          style='font-size:12.0pt;font-family:""Times New Roman"",serif;mso-fareast-font-family:
                          ""Times New Roman""'> 850Mhz, 900Mhz, 1800Mhz, 1900Mhz, 2100Mhz, 2600Mhz,
                          HSDPA, LTE<o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:3'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Kućište<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Dimenzije:</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'> 152.9 x 72.7 x 7.4 mm<o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:4'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Procesor<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Tip:</span></b><span lang=EN-US
                          style='font-size:12.0pt;font-family:""Times New Roman"",serif;mso-fareast-font-family:
                          ""Times New Roman""'> Octa-core, Hisilicon Kirin 710, Mali-G51 MP4<br>
                          <b>Takt:</b> Quad-core 2.2 GHz Cortex-A73 &amp; Quad-core 1.7 GHz Cortex-A53<o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:5'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Baterija<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Vrsta:</span></b><span lang=EN-US
                          style='font-size:12.0pt;font-family:""Times New Roman"",serif;mso-fareast-font-family:
                          ""Times New Roman""'> Li-Po (baterija nije zamenjiva bez asistencije servisa)<br>
                          <b>Kapacitet:</b> 3340 mAh<br>
                          <b>Režim razgovora:</b> do 22 h (3G)<br>
                          <b>Stand by režim:</b> do 595 h (3G)<o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:6'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Ostalo<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Ostalo:</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'> dual sim, vibracija, senzor
                          otisak prsta, digitalni kompas, akcelerometar, Gyroscope<o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:7'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Ekran<o:p></o:p></span></b></p>
                          </td>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Glavni<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Tip:</span></b><span lang=EN-US
                          style='font-size:12.0pt;font-family:""Times New Roman"",serif;mso-fareast-font-family:
                          ""Times New Roman""'> LTPS IPS LCD (6.15 inča) capacitive<br>
                          <b>Broj boja:</b> (24-bit) 16.777.216 boja<br>
                          <b>Rezolucija:</b> 1080x2312 piksela<br>
                          <b>Ostalo:</b> osetljiv na dodir, sposobnost dodira ekrana da registruje više
                          različitih pozicija, EMUI 9.0<o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:8'>
                          <td width=""15%"" rowspan=2 valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Kamera<o:p></o:p></span></b></p>
                          </td>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Glavna<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Orijentacija sočiva:</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'> sa zadnje strane<br>
                          <b>Broj piksela senzora:</b> 48 MP (f1.8, wide, PDAF) + 8 MP (13mm ultrawide)
                          + 2 MP (f/2.4, depth sensor)<br>
                          <b>Rezolucija fotografija:</b> 5290x4512 piksela<br>
                          <b>Rezolucija videa:</b> 1080p@30fps (gyro-EIS)<br>
                          <b>Ostalo:</b> video zapis, LED blic, digitalni zoom, automatsko označavanje
                          lokacije, detekcija lica, HDR, panorama mod<o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:9'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Pomoćna<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Orijentacija sočiva:</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'> sa prednje strane<br>
                          <b>Broj piksela senzora:</b> 24 megapiksela<br>
                          <b>Rezolucija videa:</b> 1080p@30fps<br>
                          <b>Ostalo:</b> f/2.0, HDR<o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:10'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Zvuk<o:p></o:p></span></b></p>
                          </td>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Reprodukcija<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Zvučnici:</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'> mono zvučnik sa ugrađenim
                          pojačalom<br>
                          <b>Melodije:</b> polifone<br>
                          <b>Format melodija:</b> mp3, aac, aac+, eaac+, flac, wav, ogg, midi, amr<br>
                          <b>Ostalo:</b> spikerfon, specijalan mikrofon za smanjenje buke<o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:11'>
                          <td width=""15%"" rowspan=2 valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Memorija<o:p></o:p></span></b></p>
                          </td>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Interna<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Kapacitet:</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'> 128 GB (4 GB RAM)<o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:12'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Eksterna<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Formati:</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'> microSD (Trans Flash),Maximalno
                          podržano : 512 GB (shared SIM slot)<br>
                          <b>Uz aparat:</b> ne ide kartica<o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:13'>
                          <td width=""15%"" rowspan=3 valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Softver<o:p></o:p></span></b></p>
                          </td>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Operativni <br>
                          sistem<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Tip:</span></b><span lang=EN-US
                          style='font-size:12.0pt;font-family:""Times New Roman"",serif;mso-fareast-font-family:
                          ""Times New Roman""'> Android OS<br>
                          <b>Verzija:</b> v9.0 (Pie)<br>
                          <b>Formati:</b> mpeg4, H.263, H.264, xvid, wmv<o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:14'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Java<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Profil:</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'> ne<br>
                          <b>Konfiguracija:</b> podržava isključivo Nano SIM karticu, čitač dokumenata<o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:15'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Funkcije<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Osnovne:</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'> kalkulator, kalendar, alarm,
                          digitalni sat, notes, podsetnik, štoperica<br>
                          <b>Napredne:</b> komandovanje glasom, pozivanje glasom, snimanje glasa<o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:16'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Komunikacija<o:p></o:p></span></b></p>
                          </td>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Udaljeno<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Prenos podataka:</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'> GSM (9,6 Kb/s), GPRS (115 Kb/s),
                          EDGE (236 Kb/s), HSDPA, LTE<br>
                          <b>WAP pretraživač:</b> HTML5<br>
                          <b>Email protokoli:</b> IMAP, POP3, SMTP, Microsoft Exchange<br>
                          <b>Ostalo:</b> SMS, MMS, Email, Push Mail, IM<o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:17;mso-yfti-lastrow:yes'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Povezivanje<o:p></o:p></span></b></p>
                          </td>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Podržane <br>
                          tehnologije<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>GPRS:</span></b><span lang=EN-US
                          style='font-size:12.0pt;font-family:""Times New Roman"",serif;mso-fareast-font-family:
                          ""Times New Roman""'> da<br>
                          <b>EDGE:</b> da<br>
                          <b>3G:</b> da, HSDPA, 42 Mbps; HSUPA, 5.76 Mbps; LTE, Cat6, 50 Mbps UL, 300
                          Mbps DL<br>
                          <b>WLAN:</b> da, Wi-Fi 802.11 a/b/g/n/ac, dual-band, Wi-Fi hotspot, Wi-Fi
                          Direct<br>
                          <b>Bluetooth:</b> da, v4.2 sa A2DP, LE, aptX HD<br>
                          <b>USB i spikerfon:</b> da, microUSB v2.0 (Type-C 1.0 reversible connector),
                          3.5' audio<br>
                          <b>GPS:</b> da, sa A-GPS podrškom i GLONASS, BDS<o:p></o:p></span></p>
                          </td>
                         </tr>
                        </table>",
                            Discount = 0,
                            Identifier = new Guid("10e23946-b462-4935-9c01-06da500db95a"),
                            Name = "Huawei P30 Lite Dual SIM 128GB 4GB RAM",
                            Price = 500m,
                            Tags = "Phones;Huawei;P30;Lite;",
                            UpdatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 979, DateTimeKind.Local).AddTicks(4651)
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 980, DateTimeKind.Local).AddTicks(4592),
                            Description = @"
                        <table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 width=""100%""
                         style='width:100.0%;mso-cellspacing:0cm;mso-yfti-tbllook:1184;mso-padding-alt:
                         0cm 0cm 0cm 0cm'>
                         <tr style='mso-yfti-irow:0;mso-yfti-firstrow:yes'>
                          <td width=""15%"" rowspan=2 valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Model<o:p></o:p></span></b></p>
                          </td>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Naziv<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Huawei P20 Dual SIM 64GB 4GB RAM
                          (twilight plava)</span></b><span lang=EN-US style='font-size:12.0pt;
                          font-family:""Times New Roman"",serif;mso-fareast-font-family:""Times New Roman""'><o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:1'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Poznat kao<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>EML-L29, EML-L09</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'><o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:2'>
                          <td width=""15%"" rowspan=5 valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Osnovno<o:p></o:p></span></b></p>
                          </td>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Market<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Mreže:</span></b><span lang=EN-US
                          style='font-size:12.0pt;font-family:""Times New Roman"",serif;mso-fareast-font-family:
                          ""Times New Roman""'> 850Mhz, 900Mhz, 1800Mhz, 1900Mhz, 2100Mhz, 2600Mhz,
                          HSDPA, LTE<o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:3'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Kućište<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Dimenzije:</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'> 149.1 x 70.8 x 7.7 mm<o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:4'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Procesor<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Tip:</span></b><span lang=EN-US
                          style='font-size:12.0pt;font-family:""Times New Roman"",serif;mso-fareast-font-family:
                          ""Times New Roman""'> Octa-core, HiSilicon Kirin 970, Mali-G72 MP12<br>
                          <b>Takt:</b> Quad-core 2.4 GHz Cortex-A73 &amp; quad-core 1.8 GHz Cortex-A53 <o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:5'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Baterija<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Vrsta:</span></b><span lang=EN-US
                          style='font-size:12.0pt;font-family:""Times New Roman"",serif;mso-fareast-font-family:
                          ""Times New Roman""'> Li-Ion (baterija nije zamenjiva bez asistencije servisa)<br>
                          <b>Kapacitet:</b> 3400 mAh<br>
                          <b>Režim razgovora:</b> do 20 h (3G)<br>
                          <b>Stand by režim:</b> do 585 h (3G)<o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:6'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Ostalo<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Ostalo:</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'> dual sim, vibracija, senzor
                          otisak prsta, digitalni kompas, akcelerometar, Gyroscope <o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:7'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Ekran<o:p></o:p></span></b></p>
                          </td>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Glavni<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Tip:</span></b><span lang=EN-US
                          style='font-size:12.0pt;font-family:""Times New Roman"",serif;mso-fareast-font-family:
                          ""Times New Roman""'> LTPS IPS LCD (5.8 inča) capacitive<br>
                          <b>Broj boja:</b> (24-bit) 16.777.216 boja<br>
                          <b>Rezolucija:</b> 1080x2240 piksela<br>
                          <b>Ostalo:</b> osetljiv na dodir, sposobnost dodira ekrana da registruje više
                          različitih pozicija, Emotion UI 8.1 <o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:8'>
                          <td width=""15%"" rowspan=2 valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Kamera<o:p></o:p></span></b></p>
                          </td>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Glavna<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Orijentacija sočiva:</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'> sa zadnje strane<br>
                          <b>Broj piksela senzora:</b> Dual kamera 12 MP (f/1.8, OIS) + 20 MP (f/1.6,
                          27mm)<br>
                          <b>Rezolucija fotografija:</b> 4096x3080 piksela<br>
                          <b>Rezolucija videa:</b> 2160p@30fps, 1080p@60fps, 720p@960fps<br>
                          <b>Ostalo:</b> video zapis, laser i phase detectzija autofokus, LED blic, digitalni
                          zoom, automatsko označavanje lokacije, detekcija lica, HDR, panorama mod <o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:9'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Pomoćna<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Orijentacija sočiva:</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'> sa prednje strane<br>
                          <b>Broj piksela senzora:</b> 24 megapiksela<br>
                          <b>Rezolucija videa:</b> 1080p@30fps<br>
                          <b>Ostalo:</b> f/2.0 <o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:10'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Zvuk<o:p></o:p></span></b></p>
                          </td>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Reprodukcija<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Zvučnici:</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'> mono zvučnik sa ugrađenim
                          pojačalom 24-bit/192kHz audio<br>
                          <b>Melodije:</b> polifone<br>
                          <b>Format melodija:</b> mp3, aac, aac+, eaac+, flac, wav, ogg, midi, amr<br>
                          <b>Ostalo:</b> spikerfon, specijalan mikrofon za smanjenje buke <o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:11'>
                          <td width=""15%"" rowspan=2 valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Memorija<o:p></o:p></span></b></p>
                          </td>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Interna<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Kapacitet:</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'> 64 GB (4 GB RAM)<o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:12'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Eksterna<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Formati:</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'> nema opciju za memorijsku karticu<br>
                          <b>Uz aparat:</b> ne ide kartica<o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:13'>
                          <td width=""15%"" rowspan=3 valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Softver<o:p></o:p></span></b></p>
                          </td>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Operativni <br>
                          sistem<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Tip:</span></b><span lang=EN-US
                          style='font-size:12.0pt;font-family:""Times New Roman"",serif;mso-fareast-font-family:
                          ""Times New Roman""'> Android OS<br>
                          <b>Verzija:</b> v8.1 (Oreo)<br>
                          <b>Formati:</b> mpeg4, H.263, H.264, xvid, wmv <o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:14'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Java<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Profil:</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'> ne<br>
                          <b>Konfiguracija:</b> podržava isključivo Nano SIM karticu, čitač dokumenata,
                          NFC podrška <o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:15'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Funkcije<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Osnovne:</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'> kalkulator, kalendar, alarm,
                          digitalni sat, notes, podsetnik, štoperica<br>
                          <b>Napredne:</b> komandovanje glasom, pozivanje glasom, snimanje glasa <o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:16'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Komunikacija<o:p></o:p></span></b></p>
                          </td>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Udaljeno<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Prenos podataka:</span></b><span
                          lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'> GSM (9,6 Kb/s), GPRS (115 Kb/s),
                          EDGE (236 Kb/s), HSDPA, LTE<br>
                          <b>WAP pretraživač:</b> HTML5<br>
                          <b>Email protokoli:</b> IMAP, POP3, SMTP, Microsoft Exchange<br>
                          <b>Ostalo:</b> SMS, MMS, Email, Push Mail, IM <o:p></o:p></span></p>
                          </td>
                         </tr>
                         <tr style='mso-yfti-irow:17;mso-yfti-lastrow:yes'>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Povezivanje<o:p></o:p></span></b></p>
                          </td>
                          <td width=""15%"" valign=top style='width:15.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>Podržane <br>
                          tehnologije<o:p></o:p></span></p>
                          </td>
                          <td width=""70%"" valign=top style='width:70.0%;padding:0cm 0cm 0cm 0cm'>
                          <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
                          normal'><b><span lang=EN-US style='font-size:12.0pt;font-family:""Times New Roman"",serif;
                          mso-fareast-font-family:""Times New Roman""'>GPRS:</span></b><span lang=EN-US
                          style='font-size:12.0pt;font-family:""Times New Roman"",serif;mso-fareast-font-family:
                          ""Times New Roman""'> da<br>
                          <b>EDGE:</b> da<br>
                          <b>3G:</b> da, HSDPA, 42 Mbps; HSUPA, 5.76 Mbps; LTE, Cat6, 50 Mbps UL, 300
                          Mbps DL<br>
                          <b>WLAN:</b> da, Wi-Fi 802.11 a/b/g/n/ac, dual-band, Wi-Fi hotspot, Wi-Fi
                          Direct<br>
                          <b>Bluetooth:</b> da, v4.2 sa A2DP, EDR, LE<br>
                          <b>USB i spikerfon:</b> da, microUSB 3.1 (Type-C 1.0 Reversible), nema ulaz
                          3.5' audio<br>
                          <b>GPS:</b> da, sa A-GPS podrškom i GLONASS <o:p></o:p></span></p>
                          </td>
                         </tr>
                        </table>",
                            Discount = 0,
                            Identifier = new Guid("901832ca-41b6-40e8-a783-8071037ffc36"),
                            Name = "Huawei P20 Dual SIM 64GB 4GB RAM",
                            Price = 309m,
                            Tags = "Phones;Huawei;P20;Dual-Sim;",
                            UpdatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 980, DateTimeKind.Local).AddTicks(4598)
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 980, DateTimeKind.Local).AddTicks(4934),
                            Description = "OPIS_TELEFONA",
                            Discount = 0,
                            Identifier = new Guid("a97c4048-89cb-4f7f-902f-601590df6f0c"),
                            Name = "LG V50 ThinQ 5G 128GB 6GB RAM",
                            Price = 825m,
                            Tags = "Phones;LG;V50;ThinQ;",
                            UpdatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 980, DateTimeKind.Local).AddTicks(4939)
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 980, DateTimeKind.Local).AddTicks(5116),
                            Description = "OPIS_TELEFONA",
                            Discount = 0,
                            Identifier = new Guid("98ac83ed-650a-416a-a46d-70fd35118716"),
                            Name = "LG V40 ThinQ Dual SIM 128GB 6GB RAM",
                            Price = 425m,
                            Tags = "Phones;LG;V40;ThinQ;",
                            UpdatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 980, DateTimeKind.Local).AddTicks(5121)
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 980, DateTimeKind.Local).AddTicks(5227),
                            Description = "OPIS_TELEFONA",
                            Discount = 0,
                            Identifier = new Guid("f41ec33b-e85c-4978-bcc8-2fba719111bb"),
                            Name = "Nokia 7.2 Dual SIM 128GB 6GB RAM",
                            Price = 319m,
                            Tags = "Phones;Nokia;7.2;Dual-Sim;",
                            UpdatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 980, DateTimeKind.Local).AddTicks(5233)
                        },
                        new
                        {
                            Id = 6,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 980, DateTimeKind.Local).AddTicks(5347),
                            Description = "OPIS_TELEFONA",
                            Discount = 0,
                            Identifier = new Guid("6d37215c-5b7c-4b23-a8ea-52a0516e02c1"),
                            Name = "Nokia 6.2 Dual SIM 128GB 4GB RAM",
                            Price = 255m,
                            Tags = "Phones;Nokia;6.2;Dual-Sim;",
                            UpdatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 980, DateTimeKind.Local).AddTicks(5352)
                        },
                        new
                        {
                            Id = 7,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 980, DateTimeKind.Local).AddTicks(5457),
                            Description = "OPIS_TELEFONA",
                            Discount = 0,
                            Identifier = new Guid("30d748ea-b3f9-42de-8842-e28fad27e274"),
                            Name = "Apple iPhone 11 Dual eSIM 64GB 4GB",
                            Price = 735m,
                            Tags = "Phones;Apple;iPhone;11;XI;Dual-Sim;",
                            UpdatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 980, DateTimeKind.Local).AddTicks(5462)
                        },
                        new
                        {
                            Id = 8,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 980, DateTimeKind.Local).AddTicks(5564),
                            Description = "OPIS_TELEFONA",
                            Discount = 0,
                            Identifier = new Guid("42340200-6d28-4c20-ac3c-86d68be2f01e"),
                            Name = "Apple iPhone X 64GB",
                            Price = 425m,
                            Tags = "Phones;Apple;iPhone;10;X;",
                            UpdatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 980, DateTimeKind.Local).AddTicks(5569)
                        },
                        new
                        {
                            Id = 9,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 980, DateTimeKind.Local).AddTicks(5672),
                            Description = "OPIS_TELEFONA",
                            Discount = 0,
                            Identifier = new Guid("b5a5bc49-77c7-486a-b175-5847c4feff1d"),
                            Name = "Samsung Galaxy Note 10 Lite Dual SIM 128GB 6GB RAM",
                            Price = 980m,
                            Tags = "Phones;Samsung;Galaxy;Note10;Dual-Sim;",
                            UpdatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 980, DateTimeKind.Local).AddTicks(5677)
                        },
                        new
                        {
                            Id = 10,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 980, DateTimeKind.Local).AddTicks(5794),
                            Description = "OPIS_TELEFONA",
                            Discount = 0,
                            Identifier = new Guid("e7afbd13-57b7-49c3-af95-ad9bc6adf2d7"),
                            Name = "Samsung Galaxy A50 Dual SIM 128GB 4GB RAM",
                            Price = 300m,
                            Tags = "Phones;Samsung;Galaxy;A50;Dual-Sim;",
                            UpdatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 980, DateTimeKind.Local).AddTicks(5800)
                        },
                        new
                        {
                            Id = 11,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 980, DateTimeKind.Local).AddTicks(5905),
                            Description = "OPIS_TELEFONA",
                            Discount = 0,
                            Identifier = new Guid("fc7b9d6f-018b-4f9c-bbb4-655722d401e6"),
                            Name = "Xiaomi Mi Note 10 Pro Dual SIM 256GB 8GB RAM",
                            Price = 510m,
                            Tags = "Phones;Xiaomi;Mi;Note10;Pro;Dual-Sim;",
                            UpdatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 980, DateTimeKind.Local).AddTicks(5910)
                        },
                        new
                        {
                            Id = 12,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 980, DateTimeKind.Local).AddTicks(6069),
                            Description = "OPIS_TELEFONA",
                            Discount = 0,
                            Identifier = new Guid("fdaa271b-b274-4c84-8bee-086049fbb8b2"),
                            Name = "Xiaomi Mi 9 Lite Dual SIM 128GB 6GB RAM",
                            Price = 350m,
                            Tags = "Phones;Xiaomi;Mi;9;Lite;Dual-Sim;",
                            UpdatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 980, DateTimeKind.Local).AddTicks(6075)
                        });
                });

            modelBuilder.Entity("Domain.Products.ProductPhoto", b =>
                {
                    b.Property<int?>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("text");

                    b.Property<bool>("MainPhoto")
                        .HasColumnType("boolean");

                    b.HasKey("ProductId", "PhotoPath");

                    b.ToTable("ProductPhotos");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            PhotoPath = "/photos/phones/huawei/Huawei_P30_Lite_Blue_Front.jpg",
                            MainPhoto = true
                        },
                        new
                        {
                            ProductId = 2,
                            PhotoPath = "/photos/phones/huawei/Huawei_P20_Twilight_Front.jpg",
                            MainPhoto = true
                        },
                        new
                        {
                            ProductId = 3,
                            PhotoPath = "/photos/phones/LG/LG_V50_ThinQ_5G_Black_Front.jpg",
                            MainPhoto = true
                        },
                        new
                        {
                            ProductId = 4,
                            PhotoPath = "/photos/phones/LG/LG_V40_Thinq_Platinum_Grey_Front.jpg",
                            MainPhoto = true
                        },
                        new
                        {
                            ProductId = 5,
                            PhotoPath = "/photos/phones/Nokia/Nokia_7-2_Green_Front.jpg",
                            MainPhoto = true
                        },
                        new
                        {
                            ProductId = 6,
                            PhotoPath = "/photos/phones/Nokia/Nokia_6-2_Black_Front.jpg",
                            MainPhoto = true
                        },
                        new
                        {
                            ProductId = 7,
                            PhotoPath = "/photos/phones/Apple/Apple_iPhone_11_Yellow_Front.jpg",
                            MainPhoto = true
                        },
                        new
                        {
                            ProductId = 8,
                            PhotoPath = "/photos/phones/Apple/Apple_iPhone_X_Space_Grey_Front.jpg",
                            MainPhoto = true
                        },
                        new
                        {
                            ProductId = 9,
                            PhotoPath = "/photos/phones/Samsung/Samsung_Galaxy_Note_10_Lite_Aura_Black_Front.jpg",
                            MainPhoto = true
                        },
                        new
                        {
                            ProductId = 10,
                            PhotoPath = "/photos/phones/Samsung/Samsung_Galaxy_A50_Black_Front.jpg",
                            MainPhoto = true
                        },
                        new
                        {
                            ProductId = 11,
                            PhotoPath = "/photos/phones/Xiaomi/Xiaomi_Mi_Note-Pro_10_Green_Front.jpg",
                            MainPhoto = true
                        },
                        new
                        {
                            ProductId = 12,
                            PhotoPath = "/photos/phones/Xiaomi/Xiaomi_Mi_9_Lite_White_Front.jpg",
                            MainPhoto = true
                        });
                });

            modelBuilder.Entity("Domain.Products.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("Identifier")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("ParentProductTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParentProductTypeId");

                    b.ToTable("ProductTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 977, DateTimeKind.Local).AddTicks(1564),
                            Description = "Phones",
                            Identifier = new Guid("d1f65fb5-d316-456e-8d52-9e23b38e5c86"),
                            Name = "Phones",
                            UpdatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 977, DateTimeKind.Local).AddTicks(2351)
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 977, DateTimeKind.Local).AddTicks(3228),
                            Description = "Masks",
                            Identifier = new Guid("26b87454-bbdd-4f37-a28d-07505b34773f"),
                            Name = "Masks",
                            UpdatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 977, DateTimeKind.Local).AddTicks(3255)
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 977, DateTimeKind.Local).AddTicks(3283),
                            Description = "Chargers",
                            Identifier = new Guid("fbb64771-e567-42a1-bd9c-c609df48d38a"),
                            Name = "Chargers",
                            UpdatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 977, DateTimeKind.Local).AddTicks(3288)
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 977, DateTimeKind.Local).AddTicks(3304),
                            Description = "Earphones",
                            Identifier = new Guid("12727ea7-a8cf-48cd-a14f-ad7604c94d38"),
                            Name = "Earphones",
                            UpdatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 977, DateTimeKind.Local).AddTicks(3308)
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 977, DateTimeKind.Local).AddTicks(3324),
                            Description = "Batteries",
                            Identifier = new Guid("d58c884d-2212-4d70-a6a1-c691456b461d"),
                            Name = "Batteries",
                            UpdatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 977, DateTimeKind.Local).AddTicks(3329)
                        },
                        new
                        {
                            Id = 6,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 977, DateTimeKind.Local).AddTicks(4158),
                            Description = "Huawei",
                            Identifier = new Guid("03d104cb-b203-4acb-b55d-249286193c74"),
                            Name = "Huawei",
                            ParentProductTypeId = 1,
                            UpdatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 977, DateTimeKind.Local).AddTicks(4179)
                        },
                        new
                        {
                            Id = 7,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 977, DateTimeKind.Local).AddTicks(4221),
                            Description = "LG",
                            Identifier = new Guid("0905aef8-d09a-4c4c-ae7f-8f9fbe31c5fd"),
                            Name = "LG",
                            ParentProductTypeId = 1,
                            UpdatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 977, DateTimeKind.Local).AddTicks(4227)
                        },
                        new
                        {
                            Id = 8,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 977, DateTimeKind.Local).AddTicks(4243),
                            Description = "Nokia",
                            Identifier = new Guid("17c55dd0-5a6a-4d23-a4cf-2878dea29aba"),
                            Name = "Nokia",
                            ParentProductTypeId = 1,
                            UpdatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 977, DateTimeKind.Local).AddTicks(4248)
                        },
                        new
                        {
                            Id = 9,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 977, DateTimeKind.Local).AddTicks(4273),
                            Description = "Apple",
                            Identifier = new Guid("eb23f964-b8ed-407e-8a5d-15a0877ee8e7"),
                            Name = "Apple",
                            ParentProductTypeId = 1,
                            UpdatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 977, DateTimeKind.Local).AddTicks(4278)
                        },
                        new
                        {
                            Id = 10,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 977, DateTimeKind.Local).AddTicks(4295),
                            Description = "Samsung",
                            Identifier = new Guid("1a9fc1dc-c13e-41a8-9ad4-bbe0486fb8f5"),
                            Name = "Samsung",
                            ParentProductTypeId = 1,
                            UpdatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 977, DateTimeKind.Local).AddTicks(4300)
                        },
                        new
                        {
                            Id = 11,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 977, DateTimeKind.Local).AddTicks(4317),
                            Description = "Xiaomi",
                            Identifier = new Guid("0956de62-01c4-4c49-bf86-ba67b6d8e498"),
                            Name = "Xiaomi",
                            ParentProductTypeId = 1,
                            UpdatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 977, DateTimeKind.Local).AddTicks(4322)
                        },
                        new
                        {
                            Id = 12,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 977, DateTimeKind.Local).AddTicks(4338),
                            Description = "Huawei",
                            Identifier = new Guid("bbac2473-ac5b-42e2-bd85-5cf53d860d3f"),
                            Name = "Huawei",
                            ParentProductTypeId = 2,
                            UpdatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 977, DateTimeKind.Local).AddTicks(4343)
                        },
                        new
                        {
                            Id = 13,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 977, DateTimeKind.Local).AddTicks(4359),
                            Description = "LG",
                            Identifier = new Guid("6c58ef05-8bba-4ba3-a485-cacd0b233d1f"),
                            Name = "LG",
                            ParentProductTypeId = 2,
                            UpdatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 977, DateTimeKind.Local).AddTicks(4364)
                        },
                        new
                        {
                            Id = 14,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 977, DateTimeKind.Local).AddTicks(4380),
                            Description = "Nokia",
                            Identifier = new Guid("82025b2e-d09d-4b98-ad48-9706a981f335"),
                            Name = "Nokia",
                            ParentProductTypeId = 2,
                            UpdatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 977, DateTimeKind.Local).AddTicks(4384)
                        },
                        new
                        {
                            Id = 15,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 977, DateTimeKind.Local).AddTicks(4403),
                            Description = "Apple",
                            Identifier = new Guid("10217421-d8b6-423a-ba26-8bb10d36e0a2"),
                            Name = "Apple",
                            ParentProductTypeId = 2,
                            UpdatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 977, DateTimeKind.Local).AddTicks(4407)
                        },
                        new
                        {
                            Id = 16,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 977, DateTimeKind.Local).AddTicks(4423),
                            Description = "Samsung",
                            Identifier = new Guid("3c368114-f279-438f-82b4-8c99a35bd7e0"),
                            Name = "Samsung",
                            ParentProductTypeId = 2,
                            UpdatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 977, DateTimeKind.Local).AddTicks(4428)
                        },
                        new
                        {
                            Id = 17,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 977, DateTimeKind.Local).AddTicks(4449),
                            Description = "Xiaomi",
                            Identifier = new Guid("1f8db86d-c166-4c7e-97d7-5d49bd23927b"),
                            Name = "Xiaomi",
                            ParentProductTypeId = 2,
                            UpdatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 977, DateTimeKind.Local).AddTicks(4454)
                        },
                        new
                        {
                            Id = 18,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 977, DateTimeKind.Local).AddTicks(4470),
                            Description = "Huawei",
                            Identifier = new Guid("ea5df040-9384-43b5-bb72-808adc57af7a"),
                            Name = "Huawei",
                            ParentProductTypeId = 4,
                            UpdatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 977, DateTimeKind.Local).AddTicks(4474)
                        },
                        new
                        {
                            Id = 19,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 977, DateTimeKind.Local).AddTicks(4490),
                            Description = "LG",
                            Identifier = new Guid("684c5d8d-cbc9-4003-84a8-4fcccf3e53b3"),
                            Name = "LG",
                            ParentProductTypeId = 4,
                            UpdatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 977, DateTimeKind.Local).AddTicks(4495)
                        },
                        new
                        {
                            Id = 20,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 977, DateTimeKind.Local).AddTicks(4511),
                            Description = "Nokia",
                            Identifier = new Guid("d435bbfb-8169-4127-902f-a56fcbf7c111"),
                            Name = "Nokia",
                            ParentProductTypeId = 4,
                            UpdatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 977, DateTimeKind.Local).AddTicks(4516)
                        },
                        new
                        {
                            Id = 21,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 977, DateTimeKind.Local).AddTicks(4532),
                            Description = "Apple",
                            Identifier = new Guid("c73da2f7-c2ac-4b26-8fc1-6897d4e51321"),
                            Name = "Apple",
                            ParentProductTypeId = 4,
                            UpdatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 977, DateTimeKind.Local).AddTicks(4536)
                        },
                        new
                        {
                            Id = 22,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 977, DateTimeKind.Local).AddTicks(4552),
                            Description = "Samsung",
                            Identifier = new Guid("734eaa53-473d-4367-9dfd-57a53727b6d5"),
                            Name = "Samsung",
                            ParentProductTypeId = 4,
                            UpdatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 977, DateTimeKind.Local).AddTicks(4557)
                        },
                        new
                        {
                            Id = 23,
                            Active = true,
                            CreatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 977, DateTimeKind.Local).AddTicks(4573),
                            Description = "Xiaomi",
                            Identifier = new Guid("6ba8a0b7-e3a2-42ab-9144-cc1d297e6a58"),
                            Name = "Xiaomi",
                            ParentProductTypeId = 4,
                            UpdatedAt = new DateTime(2020, 2, 27, 14, 17, 6, 977, DateTimeKind.Local).AddTicks(4577)
                        });
                });

            modelBuilder.Entity("Domain.Products.Product_ProductType", b =>
                {
                    b.Property<int?>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProductTypeId")
                        .HasColumnType("integer");

                    b.HasKey("ProductId", "ProductTypeId");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("Product_ProductType");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            ProductTypeId = 6
                        },
                        new
                        {
                            ProductId = 2,
                            ProductTypeId = 6
                        },
                        new
                        {
                            ProductId = 3,
                            ProductTypeId = 7
                        },
                        new
                        {
                            ProductId = 4,
                            ProductTypeId = 7
                        },
                        new
                        {
                            ProductId = 5,
                            ProductTypeId = 8
                        },
                        new
                        {
                            ProductId = 6,
                            ProductTypeId = 8
                        },
                        new
                        {
                            ProductId = 7,
                            ProductTypeId = 9
                        },
                        new
                        {
                            ProductId = 8,
                            ProductTypeId = 9
                        },
                        new
                        {
                            ProductId = 9,
                            ProductTypeId = 10
                        },
                        new
                        {
                            ProductId = 10,
                            ProductTypeId = 9
                        },
                        new
                        {
                            ProductId = 11,
                            ProductTypeId = 11
                        },
                        new
                        {
                            ProductId = 12,
                            ProductTypeId = 11
                        });
                });

            modelBuilder.Entity("Domain.Products.ProductPhoto", b =>
                {
                    b.HasOne("Domain.Products.Product", "Product")
                        .WithMany("ProductPhotos")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Products.ProductType", b =>
                {
                    b.HasOne("Domain.Products.ProductType", "ParentProductType")
                        .WithMany("SubTypes")
                        .HasForeignKey("ParentProductTypeId");
                });

            modelBuilder.Entity("Domain.Products.Product_ProductType", b =>
                {
                    b.HasOne("Domain.Products.Product", "Product")
                        .WithMany("Product_ProductTypes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Products.ProductType", "ProductType")
                        .WithMany("Product_ProductTypes")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
