version: '3.4'

services:
  ui:
    image: ${DOCKER_REGISTRY-}ui
    container_name: 'UI'
    build:
      context: .
      dockerfile: UI\Dockerfile
    networks:
      webNetwork:
        ipv4_address: 10.5.0.5

  api:
    image: ${DOCKER_REGISTRY-}api
    container_name: 'API'
    build:
      context: .
      dockerfile: API\Dockerfile
    networks:
      webNetwork:
        ipv4_address: 10.5.0.6
    depends_on:
     - db

  db:
    image: ${DOCKER_REGISTRY-}db
    container_name: 'DB'
    build:
      context: .
      dockerfile: API\DB\Postgres\Dockerfile
    networks:
      webNetwork:
        ipv4_address: 10.5.0.7
  nginx:
    image: ${DOCKER_REGISTRY-}nginx
    container_name: 'NGINX'
    build:
      context: .
      dockerfile: API\DB\Nginx\Dockerfile
    networks:
      webNetwork:
        ipv4_address: 10.5.0.8



networks:
  webNetwork:
    driver: nat
    ipam:
     config:
       - subnet: 10.5.0.0/16